// ignore_for_file: constant_identifier_names

import 'package:flutter/widgets.dart';

class KimikoIcons {
  KimikoIcons._();

  static const _kFontFam = 'KimikoIcons';
  static const String _kFontPkg = 'kimiko';

  static const IconData x_circle =
      IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData x_circle_fill =
      IconData(0xe803, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData zap =
      IconData(0xe805, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData zoom_in =
      IconData(0xe807, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData zoom_out =
      IconData(0xe809, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData accessibility =
      IconData(0xe80b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData accessibility_inset =
      IconData(0xe80c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData alert =
      IconData(0xe80d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData alert_fill =
      IconData(0xe810, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData apps =
      IconData(0xe812, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData archive =
      IconData(0xe813, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData arrow_both =
      IconData(0xe815, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData arrow_down =
      IconData(0xe817, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData arrow_down_left =
      IconData(0xe819, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData arrow_down_right =
      IconData(0xe81b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData arrow_left =
      IconData(0xe81d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData arrow_right =
      IconData(0xe81f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData arrow_switch =
      IconData(0xe821, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData arrow_up =
      IconData(0xe823, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData arrow_up_left =
      IconData(0xe825, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData arrow_up_right =
      IconData(0xe827, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData beaker =
      IconData(0xe829, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData bell =
      IconData(0xe82b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData bell_fill =
      IconData(0xe82d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData bell_slash =
      IconData(0xe82f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData blocked =
      IconData(0xe831, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData bold =
      IconData(0xe833, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData book =
      IconData(0xe835, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData bookmark =
      IconData(0xe837, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData bookmark_slash =
      IconData(0xe83a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData briefcase =
      IconData(0xe83d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData broadcast =
      IconData(0xe83f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData browser =
      IconData(0xe841, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData bug =
      IconData(0xe843, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData cache =
      IconData(0xe845, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData calendar =
      IconData(0xe846, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData check =
      IconData(0xe848, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData checkbox =
      IconData(0xe84a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData check_circle =
      IconData(0xe84c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData check_circle_fill =
      IconData(0xe84f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData checklist =
      IconData(0xe851, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData chevron_down =
      IconData(0xe854, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData chevron_left =
      IconData(0xe856, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData chevron_right =
      IconData(0xe859, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData chevron_up =
      IconData(0xe85c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData circle =
      IconData(0xe85e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData circle_slash =
      IconData(0xe860, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData clock =
      IconData(0xe862, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData clock_fill =
      IconData(0xe864, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData cloud =
      IconData(0xe866, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData cloud_offline =
      IconData(0xe868, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData code =
      IconData(0xe86a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData code_of_conduct =
      IconData(0xe86c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData code_review =
      IconData(0xe86e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData codescan =
      IconData(0xe870, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData codescan_checkmark =
      IconData(0xe872, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData codespaces =
      IconData(0xe874, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData code_square =
      IconData(0xe876, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData columns =
      IconData(0xe878, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData command_palette =
      IconData(0xe87a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData comment =
      IconData(0xe87c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData comment_discussion =
      IconData(0xe87e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData container =
      IconData(0xe881, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData copilot =
      IconData(0xe883, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData copilot_24 =
      IconData(0xe884, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData copilot_48 =
      IconData(0xe885, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData copilot_96 =
      IconData(0xe886, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData copilot_error =
      IconData(0xe887, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData copilot_warning =
      IconData(0xe888, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData copy =
      IconData(0xe889, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData cpu =
      IconData(0xe88b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData credit_card =
      IconData(0xe88d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData cross_reference =
      IconData(0xe88f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData dash =
      IconData(0xe891, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData database =
      IconData(0xe893, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData dependabot =
      IconData(0xe895, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData desktop_download =
      IconData(0xe897, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData device_camera =
      IconData(0xe899, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData device_camera_video =
      IconData(0xe89a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData device_desktop =
      IconData(0xe89c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData device_mobile =
      IconData(0xe89e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData devices =
      IconData(0xe8a0, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData diamond =
      IconData(0xe8a2, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData diff =
      IconData(0xe8a4, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData diff_added =
      IconData(0xe8a6, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData diff_ignored =
      IconData(0xe8a7, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData diff_modified =
      IconData(0xe8a8, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData diff_removed =
      IconData(0xe8a9, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData diff_renamed =
      IconData(0xe8aa, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData discussion_closed =
      IconData(0xe8ab, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData discussion_duplicate =
      IconData(0xe8ad, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData discussion_outdated =
      IconData(0xe8af, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData dot =
      IconData(0xe8b1, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData dot_fill =
      IconData(0xe8b3, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData download =
      IconData(0xe8b5, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData duplicate =
      IconData(0xe8b7, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData ellipsis =
      IconData(0xe8b9, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData eye =
      IconData(0xe8ba, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData eye_closed =
      IconData(0xe8bc, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData feed_discussion =
      IconData(0xe8be, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData feed_forked =
      IconData(0xe8bf, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData feed_heart =
      IconData(0xe8c0, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData feed_issue_closed =
      IconData(0xe8c1, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData feed_issue_draft =
      IconData(0xe8c2, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData feed_issue_open =
      IconData(0xe8c3, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData feed_issue_reopen =
      IconData(0xe8c4, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData feed_merged =
      IconData(0xe8c5, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData feed_person =
      IconData(0xe8c6, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData feed_plus =
      IconData(0xe8c7, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData feed_public =
      IconData(0xe8c8, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData feed_pull_request_closed =
      IconData(0xe8c9, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData feed_pull_request_draft =
      IconData(0xe8ca, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData feed_pull_request_open =
      IconData(0xe8cb, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData feed_repo =
      IconData(0xe8cc, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData feed_rocket =
      IconData(0xe8cd, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData feed_star =
      IconData(0xe8ce, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData feed_tag =
      IconData(0xe8cf, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData feed_trophy =
      IconData(0xe8d0, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData file =
      IconData(0xe8d1, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData file_added =
      IconData(0xe8d3, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData file_badge =
      IconData(0xe8d4, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData file_binary =
      IconData(0xe8d5, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData file_code =
      IconData(0xe8d7, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData file_diff =
      IconData(0xe8d9, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData file_directory =
      IconData(0xe8db, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData file_directory_fill =
      IconData(0xe8dd, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData file_directory_open_fill =
      IconData(0xe8df, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData file_directory_symlink =
      IconData(0xe8e0, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData file_moved =
      IconData(0xe8e3, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData file_removed =
      IconData(0xe8e4, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData file_submodule =
      IconData(0xe8e5, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData file_symlink_file =
      IconData(0xe8e7, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData file_zip =
      IconData(0xe8e9, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData filter =
      IconData(0xe8eb, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData fiscal_host =
      IconData(0xe8ed, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData flame =
      IconData(0xe8ee, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData fold =
      IconData(0xe8f0, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData fold_down =
      IconData(0xe8f2, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData fold_up =
      IconData(0xe8f4, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData gear =
      IconData(0xe8f6, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData gift =
      IconData(0xe8f8, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData git_branch =
      IconData(0xe8fa, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData git_commit =
      IconData(0xe8fc, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData git_compare =
      IconData(0xe8fe, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData git_merge =
      IconData(0xe900, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData git_merge_queue =
      IconData(0xe902, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData git_pull_request =
      IconData(0xe904, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData git_pull_request_closed =
      IconData(0xe906, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData git_pull_request_draft =
      IconData(0xe908, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData globe =
      IconData(0xe90a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData goal =
      IconData(0xe90c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData grabber =
      IconData(0xe90e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData graph =
      IconData(0xe910, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData hash =
      IconData(0xe912, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData heading =
      IconData(0xe914, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData heart =
      IconData(0xe916, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData heart_fill =
      IconData(0xe918, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData history =
      IconData(0xe91a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData home =
      IconData(0xe91c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData horizontal_rule =
      IconData(0xe91f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData hourglass =
      IconData(0xe921, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData hubot =
      IconData(0xe923, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData id_badge =
      IconData(0xe925, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData image =
      IconData(0xe926, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData inbox =
      IconData(0xe928, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData infinity =
      IconData(0xe92a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData info =
      IconData(0xe92c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData issue_closed =
      IconData(0xe92e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData issue_draft =
      IconData(0xe930, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData issue_opened =
      IconData(0xe932, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData issue_reopened =
      IconData(0xe934, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData issue_tracked_by =
      IconData(0xe936, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData issue_tracks =
      IconData(0xe938, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData italic =
      IconData(0xe93a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData iterations =
      IconData(0xe93c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData kebab_horizontal =
      IconData(0xe93e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData key =
      IconData(0xe940, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData key_asterisk =
      IconData(0xe942, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData law =
      IconData(0xe943, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData light_bulb =
      IconData(0xe945, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData link =
      IconData(0xe947, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData link_external =
      IconData(0xe949, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData list_ordered =
      IconData(0xe94b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData list_unordered =
      IconData(0xe94d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData location =
      IconData(0xe94f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData lock =
      IconData(0xe951, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData log =
      IconData(0xe953, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData logo_gist =
      IconData(0xe955, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData logo_github =
      IconData(0xe956, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData mail =
      IconData(0xe957, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData markdown =
      IconData(0xe959, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData mark_github =
      IconData(0xe95a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData megaphone =
      IconData(0xe95b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData mention =
      IconData(0xe95d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData meter =
      IconData(0xe95f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData milestone =
      IconData(0xe960, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData mirror =
      IconData(0xe962, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData moon =
      IconData(0xe964, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData mortar_board =
      IconData(0xe966, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData move_to_bottom =
      IconData(0xe968, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData move_to_end =
      IconData(0xe96a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData move_to_start =
      IconData(0xe96c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData move_to_top =
      IconData(0xe96e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData multi_select =
      IconData(0xe970, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData mute =
      IconData(0xe972, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData no_entry =
      IconData(0xe974, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData north_star =
      IconData(0xe977, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData note =
      IconData(0xe979, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData number =
      IconData(0xe97b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData organization =
      IconData(0xe97d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData package =
      IconData(0xe97f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData package_dependencies =
      IconData(0xe981, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData package_dependents =
      IconData(0xe983, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData paintbrush =
      IconData(0xe985, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData paper_airplane =
      IconData(0xe986, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData paperclip =
      IconData(0xe988, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData passkey_fill =
      IconData(0xe98a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData paste =
      IconData(0xe98c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData pencil =
      IconData(0xe98e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData people =
      IconData(0xe990, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData person =
      IconData(0xe992, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData person_add =
      IconData(0xe994, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData person_fill =
      IconData(0xe996, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData pin =
      IconData(0xe998, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData pin_slash =
      IconData(0xe99a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData pivot_column =
      IconData(0xe99c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData play =
      IconData(0xe99e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData plug =
      IconData(0xe9a0, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData plus =
      IconData(0xe9a2, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData plus_circle =
      IconData(0xe9a4, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData project =
      IconData(0xe9a6, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData project_roadmap =
      IconData(0xe9a8, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData project_symlink =
      IconData(0xe9aa, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData project_template =
      IconData(0xe9ac, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData pulse =
      IconData(0xe9ae, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData question =
      IconData(0xe9b0, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData quote =
      IconData(0xe9b2, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData read =
      IconData(0xe9b4, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData redo =
      IconData(0xe9b6, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData rel_file_path =
      IconData(0xe9b7, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData reply =
      IconData(0xe9b9, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData repo =
      IconData(0xe9bb, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData repo_clone =
      IconData(0xe9bd, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData repo_deleted =
      IconData(0xe9bf, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData repo_forked =
      IconData(0xe9c0, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData repo_locked =
      IconData(0xe9c2, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData repo_pull =
      IconData(0xe9c4, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData repo_push =
      IconData(0xe9c6, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData report =
      IconData(0xe9c8, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData repo_template =
      IconData(0xe9ca, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData rocket =
      IconData(0xe9cc, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData rows =
      IconData(0xe9ce, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData rss =
      IconData(0xe9d0, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData ruby =
      IconData(0xe9d2, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData screen_full =
      IconData(0xe9d4, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData screen_normal =
      IconData(0xe9d6, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData search =
      IconData(0xe9d8, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData server =
      IconData(0xe9da, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData share =
      IconData(0xe9dc, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData share_android =
      IconData(0xe9de, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData shield =
      IconData(0xe9e0, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData shield_check =
      IconData(0xe9e2, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData shield_lock =
      IconData(0xe9e4, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData shield_slash =
      IconData(0xe9e6, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData shield_x =
      IconData(0xe9e8, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData sidebar_collapse =
      IconData(0xe9ea, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData sidebar_expand =
      IconData(0xe9ec, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData sign_in =
      IconData(0xe9ee, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData sign_out =
      IconData(0xe9f0, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData single_select =
      IconData(0xe9f2, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData skip =
      IconData(0xe9f4, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData skip_fill =
      IconData(0xe9f6, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData sliders =
      IconData(0xe9f8, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData smiley =
      IconData(0xe9f9, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData sort_asc =
      IconData(0xe9fb, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData sort_desc =
      IconData(0xe9fd, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData sparkle_fill =
      IconData(0xe9ff, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData sponsor_tiers =
      IconData(0xea00, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData square =
      IconData(0xea02, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData square_fill =
      IconData(0xea04, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData squirrel =
      IconData(0xea06, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData stack =
      IconData(0xea08, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData star =
      IconData(0xea0a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData star_fill =
      IconData(0xea0c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData stop =
      IconData(0xea0e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData stopwatch =
      IconData(0xea10, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData strikethrough =
      IconData(0xea12, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData sun =
      IconData(0xea14, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData sync =
      IconData(0xea16, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData tab_external =
      IconData(0xea19, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData table =
      IconData(0xea1a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData tag =
      IconData(0xea1c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData tasklist =
      IconData(0xea1e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData telescope =
      IconData(0xea20, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData telescope_fill =
      IconData(0xea22, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData terminal =
      IconData(0xea24, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData three_bars =
      IconData(0xea26, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData thumbsdown =
      IconData(0xea27, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData thumbsup =
      IconData(0xea29, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData tools =
      IconData(0xea2b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData tracked_by_closed_completed =
      IconData(0xea2d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData tracked_by_closed_not_planned =
      IconData(0xea2f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData trash =
      IconData(0xea31, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData triangle_down =
      IconData(0xea33, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData triangle_left =
      IconData(0xea35, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData triangle_right =
      IconData(0xea37, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData triangle_up =
      IconData(0xea39, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData trophy =
      IconData(0xea3b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData typography =
      IconData(0xea3d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData undo =
      IconData(0xea3f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData unfold =
      IconData(0xea40, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData unlink =
      IconData(0xea42, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData unlock =
      IconData(0xea44, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData unmute =
      IconData(0xea46, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData unread =
      IconData(0xea48, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData unverified =
      IconData(0xea4a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData upload =
      IconData(0xea4c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData verified =
      IconData(0xea4e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData versions =
      IconData(0xea50, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData video =
      IconData(0xea52, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData webhook =
      IconData(0xea54, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData workflow =
      IconData(0xea55, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData x =
      IconData(0xea58, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
