/// This file contains **Prototypal Strings Extension Pattern**.

import 'package:flutter/cupertino.dart' show Locale;

/// This enum contains all the string keys used in the app.
enum _KimikoStringKey {
  dashboard,
  user,
  users,
  noUser,
  home,
  email,
  password,
  phone,
  isRequired,
  mustMatchPassword,
  isInvalid,
  dateMustBeBefore,
  dateMustBeAfter,
  from,
  from_,
  to,
  to_,
  at,
  date,
  month,
  day,
  year,
  emails,
  dates,
  months,
  days,
  years,
  searchForCountry,
  search,
  lastPick,
  pickCountry,
  resendCode,
  codeNotReceived,
  yes,
  no,
  ok,
  about,
  warning,
  warnings,
  accept,
  refuse,
  decline,
  end,
  start,
  end_,
  start_,
  active,
  active_,
  inactive,
  inactive_,
  activate,
  deactivate,
  terminate,
  cloture,
  cancel,
  comment,
  review,
  comment_,
  comments,
  reviews,
  send,
  add,
  remove,
  delete,
  modify,
  save,
  call,
  mail,
  dm,
  ads_,
  ad_,
  ads,
  ad,
  enable,
  disable,
  enabled,
  disabled,
  all,
  first,
  last,
  amount,
  message,
  update,
  create,
  borrow,
  action,
  actions,
  booking,
  bookings,
  book,
  paperBook,
  other,
  male,
  female,
  man,
  woman,
  unkown,
  recent,
  connect,
  noAccount,
  createOne,
  alreadyHaveAnAccount,
  login,
  disconnect,
  confirmPassword,
  register,
  profileEmpty,
  updateProfile,
  profile,
  pictures,
  camera,
  choosePicture,
  settings,
  faq,
  faq_,
  contactUs,
  legalMentions,
  politics,
  inApp,
  options,
  title,
  features,
  price,
  total,
  type,
  categories,
  category,
  previous,
  next,
  previous_,
  next_,
  previousPage,
  nextPage,

  /// codes
  success,
  failed,
  connexionFailed,
  userInvalidCredentials,
  userCreated,
  userUpdated,
  userProfileUpdated,
  ppUpdated,
  passwordUpdated,
  wrongPassword,
  emailUpdated,
  phoneNumberUpdated,
  updateFailed,
  userConnected,
  emailAlreadyUsed,
  emailAvailable,
  phoneNumberAlreadyUsed,
  phoneNumberAvailable,
  userDisconnected,
  verificationCodeSent,
  wrongVerificationCode,
  verificationSucceed,
  verificationFailed,
  verificationFailedInvalidNumber,
  verificationFailedTooManyRequest,
  verificationFailedSessionExpired,
  congratulations,
  sendMessage,
  messageSent,
  messageNotSent,
  messageRemoved,
  messageNotRemoved,
  invalidFields,
  mustBeAtLeast,
  character,
  characters,
}

/// Type definition for [_KimikoStringKey] to more friendly [KStrings] name.
typedef KStrings = _KimikoStringKey;

/// This extension uses the [_KimikoStringKey] enum to get the string [value]
extension KimikoStringExtension on KStrings {
  String get value => KimikoStrings.instance[this];
}

/// This class contains strings, their translations and all logic related to locale configuration.
/// Usage:
/// 1. Directly use the [KStrings] enum to get the string [value] thanks to the [KimikoStringExtension] extension.
/// 2. Use the [[] operator] to get the string value by passing the [KStrings] enum to an [instance] or
///     just use the [KimikoStringExtension.value] getter
class KimikoStrings {
  const KimikoStrings._();

  static const instance = KimikoStrings._();

  static void setLocale(Locale locale) {
    if (_texts.containsKey(locale.languageCode)) {
      _locale = locale;
    }
  }

  static get defaultLocale => const Locale('en');

  static Locale _locale = defaultLocale;

  String get language => _locale.languageCode;

  String _localeText(KStrings key) => _texts[language]![key]!;

  String operator [](KStrings key) => _localeText(key);

  static const _texts = <String, Map<_KimikoStringKey, String>>{
    'fr': _fr,
    'en': _en,
  };

  // font family
  static const hpFontFamily = 'HP', signikaFontFamily = 'Signika';

  static const String phoneNumberRegex = r'^\+?[0-9]{10,13}$',
      emailRegex = r'^.+@[a-zA-Z]+\.{1}[a-zA-Z]+(\.{0,1}[a-zA-Z]+)$';

  static String mustBeAtLeast(num length, [String? unit]) =>
      instance[KStrings.mustBeAtLeast] +
      length.toString() +
      (unit ?? instance[KStrings.characters]);

  /// specials
  static const notifIcon = 'notif_icon',
      dot = '\u00b7',
      dots3 = '...',
      tab = '\t';

  // default english strings
  static const _en = {
    KStrings.dashboard: 'Dashboard',
    KStrings.user: 'User',
    KStrings.users: 'Users',
    KStrings.noUser: 'No User !',
    KStrings.home: 'Home',
    KStrings.email: 'Email',
    KStrings.password: 'Password',
    KStrings.phone: 'Phone',
    KStrings.isRequired: 'is required',
    KStrings.isInvalid: 'is invalid',
    KStrings.dateMustBeBefore: 'must be before',
    KStrings.dateMustBeAfter: 'must be after',
    KStrings.from: "from",
    KStrings.from_: "from",
    KStrings.to: "to",
    KStrings.to_: "to",
    KStrings.at: "at",
    KStrings.date: 'Date',
    KStrings.month: 'Month',
    KStrings.day: 'Day',
    KStrings.year: 'Year',
    KStrings.emails: 'Emails',
    KStrings.dates: 'Dates',
    KStrings.months: 'Months',
    KStrings.days: 'Days',
    KStrings.years: 'Years',
    KStrings.searchForCountry: 'Search for country',
    KStrings.search: 'Search',
    KStrings.lastPick: 'Last pick',
    KStrings.pickCountry: 'Pick country',
    KStrings.resendCode: 'Resend code',
    KStrings.codeNotReceived: 'Code not received?',
    KStrings.mustMatchPassword: 'must match password',
    KStrings.yes: 'Yes',
    KStrings.no: 'No',
    KStrings.ok: 'OK',
    KStrings.about: 'About',
    KStrings.warning: 'Warning',
    KStrings.warnings: 'Warnings',
    KStrings.accept: 'Accept',
    KStrings.refuse: 'Refuse',
    KStrings.decline: 'Decline',
    KStrings.end: "End",
    KStrings.start: "Start",
    KStrings.end_: "End",
    KStrings.start_: "Start",
    KStrings.active: "Active",
    KStrings.active_: "Active",
    KStrings.inactive: "Inactive",
    KStrings.inactive_: "Inactive",
    KStrings.activate: "Activate",
    KStrings.deactivate: "Deactivate",
    KStrings.terminate: "Terminate",
    KStrings.cloture: "Cloture",
    KStrings.save: "Save",
    KStrings.update: "Update",
    KStrings.delete: "Delete",
    KStrings.cancel: "Cancel",
    KStrings.comment: "Comment",
    KStrings.review: "Review",
    KStrings.comment_: "Comment",
    KStrings.comments: "Comments",
    KStrings.reviews: "Reviews",
    KStrings.create: "Create",
    KStrings.borrow: "Borrow",
    KStrings.action: "Action",
    KStrings.actions: "Actions",
    KStrings.booking: "Booking",
    KStrings.bookings: "Bookings",
    KStrings.book: "Book",
    KStrings.paperBook: "Book",
    KStrings.send: 'Send',
    KStrings.add: "Add",
    KStrings.remove: "Remove",
    KStrings.modify: "Modify",
    KStrings.call: "Call",
    KStrings.mail: "Mail",
    KStrings.dm: "Direct message",
    KStrings.ads_: "Ads",
    KStrings.ad_: "Ad",
    KStrings.ads: "Advertisements",
    KStrings.ad: "Advertisement",
    KStrings.enable: 'Enable',
    KStrings.disable: 'Disable',
    KStrings.enabled: 'Enabled',
    KStrings.disabled: 'Disabled',
    KStrings.all: 'All',
    KStrings.first: 'First',
    KStrings.last: 'Last',
    KStrings.amount: 'Amount',
    KStrings.message: 'Message',
    KStrings.other: "Other",
    KStrings.male: "Male",
    KStrings.female: "Female",
    KStrings.man: "Man",
    KStrings.woman: "Woman",
    KStrings.unkown: "Unkown",
    KStrings.recent: "Recent",
    KStrings.connect: "Connect",
    KStrings.noAccount: "No account ?",
    KStrings.createOne: "Create one !",
    KStrings.alreadyHaveAnAccount: "Already have an account ?",
    KStrings.login: "Login !",
    KStrings.disconnect: "Disconnect",
    KStrings.confirmPassword: "Confirm",
    KStrings.register: "Register",
    KStrings.profileEmpty: "Your profile is empty !",
    KStrings.updateProfile: "Update profile",
    KStrings.profile: "Profile",
    KStrings.pictures: "Pictures",
    KStrings.camera: "Camera",
    KStrings.choosePicture: "Choose a picture",
    KStrings.settings: "Settings",
    KStrings.faq: "Foire aux questions",
    KStrings.faq_: "FAQ",
    KStrings.contactUs: "Contact us",
    KStrings.legalMentions: "Legal Mentions",
    KStrings.politics: "Politics",
    KStrings.inApp: "In App",
    KStrings.options: "Options",
    KStrings.title: "Title",
    KStrings.features: "Features",
    KStrings.price: "Price",
    KStrings.total: "Total",
    KStrings.type: "Type",
    KStrings.categories: "Categories",
    KStrings.category: "Category",
    KStrings.previous: "Prev",
    KStrings.next: "Next",
    KStrings.previous_: "Previous",
    KStrings.next_: "Next",

    /// response codes
    KStrings.success: "Success",
    KStrings.failed: "Failed",
    KStrings.connexionFailed: "Connexion failed",
    KStrings.userInvalidCredentials: "Invalid credentials",
    KStrings.userCreated: "Account created",
    KStrings.userUpdated: "Account updated",
    KStrings.userProfileUpdated: "Profile updated",
    KStrings.ppUpdated: "Profile picture updated",
    KStrings.passwordUpdated: "Password updated",
    KStrings.wrongPassword: "Wrong password",
    KStrings.emailUpdated: "Email updated",
    KStrings.phoneNumberUpdated: "Phone number updated",
    KStrings.updateFailed: "Update failed",
    KStrings.userConnected: "User connected",
    KStrings.emailAlreadyUsed: "Email already used",
    KStrings.emailAvailable: "Email available",
    KStrings.phoneNumberAlreadyUsed: "Phone number already used",
    KStrings.phoneNumberAvailable: "Phone number available",
    KStrings.userDisconnected: "User disconnected",
    KStrings.verificationCodeSent: "Verification code sent",
    KStrings.wrongVerificationCode: "Wrong verification code",
    KStrings.verificationSucceed: "Verification succeed",
    KStrings.verificationFailed: "Verification failed",
    KStrings.verificationFailedInvalidNumber: "Invalid phone number",
    KStrings.verificationFailedTooManyRequest: "Too many request",
    KStrings.verificationFailedSessionExpired: "Session expired",
    KStrings.congratulations: "Congratulations !",
    KStrings.sendMessage: "Send message",
    KStrings.messageSent: "Message sent",
    KStrings.messageNotSent: "Message not sent",
    KStrings.messageRemoved: "Message removed",
    KStrings.messageNotRemoved: "Message not removed",
    KStrings.invalidFields: "Some fields may be invalid",
    KStrings.mustBeAtLeast: "must be at least ",
    KStrings.character: "Character",
    KStrings.characters: "Characters",
  };

  // default french strings
  static const _fr = {
    KStrings.dashboard: 'Tableau de bord',
    KStrings.user: 'Utilisateur',
    KStrings.users: 'Utilisateurs',
    KStrings.noUser: 'Aucun Utilisateur !',
    KStrings.home: 'Accueil',
    KStrings.email: 'Email',
    KStrings.password: 'Mot de passe',
    KStrings.phone: 'Téléphone',
    KStrings.isRequired: 'Ce champ est requis',
    KStrings.isInvalid: 'Ce champ est invalide',
    KStrings.dateMustBeBefore: 'doit être avant',
    KStrings.dateMustBeAfter: 'doit être après',
    KStrings.from: "de",
    KStrings.from_: "du",
    KStrings.to: "à",
    KStrings.to_: "au",
    KStrings.at: "à",
    KStrings.date: 'Date',
    KStrings.month: 'Mois',
    KStrings.day: 'Jour',
    KStrings.year: 'Année',
    KStrings.emails: 'Emails',
    KStrings.dates: 'Dates',
    KStrings.months: 'Mois',
    KStrings.days: 'Jours',
    KStrings.years: 'Années',
    KStrings.searchForCountry: 'Rechercher un pays',
    KStrings.search: 'Rechercher',
    KStrings.lastPick: 'Dernier choix',
    KStrings.pickCountry: 'Choisir un pays',
    KStrings.resendCode: 'Renvoyer le code',
    KStrings.codeNotReceived: 'Code non reçu ?',
    KStrings.mustMatchPassword: 'doit correspondre au mot de passe',
    KStrings.yes: 'Oui',
    KStrings.no: 'Non',
    KStrings.ok: 'OK',
    KStrings.about: 'A propos',
    KStrings.warning: 'Attention',
    KStrings.warnings: 'Attentions',
    KStrings.accept: 'Accepter',
    KStrings.refuse: 'Refuser',
    KStrings.decline: 'Décliner',
    KStrings.end: "Finir",
    KStrings.start: "Commencer",
    KStrings.end_: "Fin",
    KStrings.start_: "Début",
    KStrings.active: "Actif",
    KStrings.active_: "Active",
    KStrings.inactive: "Inactif",
    KStrings.inactive_: "Inactive",
    KStrings.activate: "Activer",
    KStrings.deactivate: "Désactiver",
    KStrings.terminate: "Terminer",
    KStrings.cloture: "Cloturer",
    KStrings.cancel: 'Annuler',
    KStrings.comment: "Commenter",
    KStrings.review: "Avis",
    KStrings.comment_: "Commentaire",
    KStrings.comments: "Commentaires",
    KStrings.reviews: "Avis",
    KStrings.send: 'Envoyer',
    KStrings.add: "Ajouter",
    KStrings.remove: "Effacer",
    KStrings.delete: "Supprimer",
    KStrings.modify: "Modifier",
    KStrings.save: "Sauvegarder",
    KStrings.call: "Appeler",
    KStrings.mail: "Mail",
    KStrings.dm: "Message direct",
    KStrings.ads_: "Pubs",
    KStrings.ad_: "Pub",
    KStrings.ads: "Publicités",
    KStrings.ad: "Publicités",
    KStrings.enable: 'Activer',
    KStrings.disable: 'Désactiver',
    KStrings.enabled: 'Activé',
    KStrings.disabled: 'Désactivé',
    KStrings.all: 'Tout',
    KStrings.first: 'Premier',
    KStrings.last: 'Dernier',
    KStrings.amount: 'Montant',
    KStrings.message: 'Message',
    KStrings.update: "Mettre à jour",
    KStrings.create: "Créer",
    KStrings.borrow: "Louer",
    KStrings.action: "Action",
    KStrings.actions: "Actions",
    KStrings.booking: "Reservation",
    KStrings.bookings: "Reservations",
    KStrings.book: "Reserver",
    KStrings.paperBook: "Livre",
    KStrings.other: "Autre",
    KStrings.male: "Masculin",
    KStrings.female: "Féminin",
    KStrings.man: "Homme",
    KStrings.woman: "Femme",
    KStrings.unkown: "Inconnu",
    KStrings.recent: "Récent",
    KStrings.connect: "Se connecter",
    KStrings.noAccount: "Pas encore de compte ?",
    KStrings.createOne: "Créez en un !",
    KStrings.alreadyHaveAnAccount: "Vous avez un compte ?",
    KStrings.login: "Connectez vous !",
    KStrings.disconnect: "Se déconnecter",
    KStrings.confirmPassword: "Confirmation",
    KStrings.register: "S'inscrire",
    KStrings.profileEmpty: "Profil non renseigné !",
    KStrings.updateProfile: "Mettre à jour",
    KStrings.profile: "Profil",
    KStrings.pictures: "Photos",
    KStrings.camera: "Appareil photo",
    KStrings.choosePicture: "Choisir une photo",
    KStrings.settings: "Paramètres",
    KStrings.faq: "Foire aux questions",
    KStrings.faq_: "FAQ",
    KStrings.contactUs: "Nous contacter",
    KStrings.legalMentions: "Mentions légales",
    KStrings.politics: "Politiques et CGV",
    KStrings.inApp: "Dans l'application",
    KStrings.options: "Options",
    KStrings.title: "Titre",
    KStrings.features: "Caractéristiques",
    KStrings.price: "Prix",
    KStrings.total: "Total",
    KStrings.type: "Type",
    KStrings.categories: "Catégories",
    KStrings.category: "Catégorie",
    KStrings.previous: "Prev",
    KStrings.next: "Next",
    KStrings.previous_: "Précédent",
    KStrings.next_: "Suivant",

    /// response codes
    KStrings.success: "Succès",
    KStrings.failed: "Echec",
    KStrings.connexionFailed: "Connexion échouée",
    KStrings.userInvalidCredentials: "Identifiants invalides",
    KStrings.userCreated: "Compte créé",
    KStrings.userUpdated: "Compte mis à jour",
    KStrings.userProfileUpdated: "Profil mis à jour",
    KStrings.ppUpdated: "Photo de profil mise à jour",
    KStrings.passwordUpdated: "Mot de passe mis à jour",
    KStrings.wrongPassword: "Mot de passe incorrect",
    KStrings.emailUpdated: "Email mis à jour",
    KStrings.phoneNumberUpdated: "Numéro de téléphone mis à jour",
    KStrings.updateFailed: "Mise à jour échouée",
    KStrings.userConnected: "Utilisateur connecté",
    KStrings.emailAlreadyUsed: "Email déjà utilisé",
    KStrings.emailAvailable: "Email disponible",
    KStrings.phoneNumberAlreadyUsed: "Numéro de téléphone déjà utilisé",
    KStrings.phoneNumberAvailable: "Numéro de téléphone disponible",
    KStrings.userDisconnected: "Utilisateur déconnecté",
    KStrings.verificationCodeSent: "Code de vérification envoyé",
    KStrings.wrongVerificationCode: "Code de vérification incorrect",
    KStrings.verificationSucceed: "Vérification réussie",
    KStrings.verificationFailed: "Vérification échouée",
    KStrings.verificationFailedInvalidNumber: "Numéro de téléphone invalide",
    KStrings.verificationFailedTooManyRequest: "Trop de requêtes",
    KStrings.verificationFailedSessionExpired: "Session expirée",
    KStrings.congratulations: "Félicitations !",
    KStrings.sendMessage: "Envoyer un message",
    KStrings.messageSent: "Message envoyé",
    KStrings.messageNotSent: "Message non envoyé",
    KStrings.messageRemoved: "Message supprimé",
    KStrings.messageNotRemoved: "Message non supprimé",
    KStrings.invalidFields: "Certains champs peuvent être invalides",
    KStrings.mustBeAtLeast: "doit être au moins ",
    KStrings.character: "Caractère",
    KStrings.characters: "Caractères",
  };

  /// firebase strings
  static const usersCollection = 'users',
      messagesCollection = 'messages',
      discussionsCollection = 'discussions',
      eventsCollection = 'events',
      interestsCollection = 'interests',
      moodsCollection = 'moods';

  /// models

  /// user fields
  static const userIdField = "id",
      userNameField = "name",
      userBioField = "bio",
      userBirthdateField = 'birthdate',
      userOnlineField = 'online',
      userInterestsField = "interests",
      userInterestInField = "interest_in",
      userPicturesField = "pictures",
      userPictureField = "picture",
      userSexField = "sex",
      userMoodField = 'mood',
      userShowOnlineField = 'show_online',
      userShowAgeField = 'show_age',
      userInterestAgesField = 'interest_ages',
      userLocateField = 'geolocation',
      userLocationField = 'location',
      userVisibleField = 'visible',
      userCreatedAtField = 'created_at',
      userSeenField = 'seen';
  // userLastSeenProfileField = 'last_seen_profile';

  /// location fields
  static const locationGeohashField = 'geohash',
      locationGeoPointField = 'geopoint';

  // sex values
  static const sexFieldValueMale = 'MALE',
      sexFieldValueFemale = 'FEMALE',
      sexFieldValueOther = 'OTHER';

  // mood fields
  static const moodUrlField = 'url',
      moodNameField = 'name',
      moodValueField = 'value',
      moodUpdatedAtField = 'updated_at';

  // matchable fields
  static const matchableIdField = "id",
      matchableUserField = "user",
      matchableLikedYouField = "liked_you",
      matchableDistanceField = "distance";

  // event fields
  static const eventIdField = "id",
      eventUserField = "user",
      eventKindField = "kind",
      eventShowField = "show",
      eventHappenedAtField = "happened_at";

  // event kind values
  static const eventKindValueVisited = "VISITED",
      eventKindValueMatched = "MATCHED",
      eventKindValueLiked = "LIKED",
      eventKindValueDisliked = "DISLIKED",
      eventKindValueReported = "REPORTED",
      eventKindValueBlocked = "BLOCKED";

  // discussion fields
  static const discussionIdField = 'id',
      discussionUsersField = 'users',
      discussionCorrespondingField = 'corresponding',
      discussionUpdatedAtField = 'updated_at',
      discussionLastMessageField = 'last_message',
      discussionUnreadField = 'unread';

  // message fields
  static const messageIdField = 'id',
      messageContentField = 'content',
      messageStickerField = 'sticker',
      messageSenderIdField = 'sender_id',
      messageReplyToField = 'reply_to',
      messageDeletedField = 'deleted',
      messageCreatedAtField = 'created_at';

  // interest fields
  static const interestIconField = "icon",
      interestIconFontField = "icon_font",
      interestNameField = "name",
      interestValueField = "value";
}
